### PR TITLE
Update Deno Deploy Pricing

### PR DESCRIPTION
**Pull request by CetinSert**
image

### CODE REVIEW

**Review by KnorpelSenf — CHANGES_REQUESTED** [review]
Thanks! Are you able to spot the same numbers on the pages of the other languages, and update them as well? Then we can merge immediately

**Comment by CetinSert** [comment]
Cloudflare Workers, and Vercel are the same.
I don't know the others.

**Comment by KnorpelSenf** [comment]
I think I wasn't clear. The website is available in 5 languages and we have a team of translators who are busy syncing things up. This means that the same number has to be fixed on the other 4 pages.

**Comment by KnorpelSenf** [comment]
Never mind, I think the other languages are very outdated for some reason. Just leave things as they are, we're gonna take care of it.

Thanks!

**Review by roj1512 — APPROVED** [review]
Thanks!

**Review by KnorpelSenf — APPROVED** [review]

**Pull request merged**
