### PR TITLE
feat: migrate to vuepress-vite

### LINKED ISSUE #49: feat: migrate vuepress to vuepress-vite or vitepress
`vuepress` is using webpack which is much slower than `vuepress-vite` or `vitepress`(they are using vite and esbuild).

I have tested the build time between `vuepress` and `vuepress-vite`, here is the result:

```
+---------+----------+---------------+
|         | vuerepss | vuepress-vite |
+---------+----------+---------------+
| Time1   | 30.29s   | 17.77s        |
| Time2   | 29.67s   | 16.87s        |
| Average | 29.98s   | 17.32s        |
+---------+----------+---------------+
```

`vuepress-vite` is **40%** faster than `vuepress` in my `i5-9500` computer.

Migrate to `vuepress-vite` is very simple and easy, or we can migrate to `vitepress`(to vitepress is a bit complicated, but I will do the job).

There will be a PR migrate to `vuepress-vite`, you can take a look about it.

### PR DESCRIPTION
**Pull request by WingLim**
Closes #49.

### CODE REVIEW

**Review by KnorpelSenf — CHANGES_REQUESTED** [review]
LGTM!

Please update the docsearch dependency to beta.27 so that it's in sync with `vuepress-vite`.

**Comment by WingLim** [comment]
@KnorpelSenf Already update docsearch to newest.

**Review by KnorpelSenf — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
@WingLim Why did this PR downgrade the lockfile version to `1`?

**Comment by WingLim** [comment]
> @WingLim Why did this PR downgrade the lockfile version to `1`?

Oops, I check my mac using `pnpm` to manage node version.
`node` and `npm` switch back to old version, and I didn't notice it.
Will upgrade it back...

**Comment by KnorpelSenf** [comment]
Yet another alternative would be to hard-code an exception for the respective paragraph in the `<wbr>` tag injection plugin. I am not too convinced that this is the right thing to do, but it would certainly work.

We could revert this change once https://github.com/vuepress/vuepress-next/issues/602 is fixed.

**Comment by KnorpelSenf** [comment]
I believe it's only the single paragraph that I linked. I read the complete docs.

**Comment by WingLim** [comment]
> I believe it's only the single paragraph that I linked. I read the complete docs.

Let's see what's @roj1512 option, I prefer the second, `vite` is faster for dev in preview.

**Comment by roj1512** [comment]
@KnorpelSenf I am not seeing any duplicate text on the guide/basics page when I run locally.

**Comment by KnorpelSenf** [comment]
That's part of the bug. This behaviour is described in the aforementioned issue.

**Comment by roj1512** [comment]
How should it get rephrased btw? Get the text out of quotes?

**Comment by KnorpelSenf** [comment]
I don't think it's happening only in the quotes, does it? We'll just have to play a bit around with it until it suddenly doesn't appear anymore. That is, unless you want to understand the bug, but at that point you might as well fix vuepress.

**Pull request merged**
