### PR TITLE
Globes for language switching

### PR DESCRIPTION
**Pull request by KnorpelSenf**
How else would I know how to switch back the language?

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]
LGTM. Thank you so much!

**Comment by roj1512** [comment]
We could use a single globe for all languages if the displayed regions are a problem.

**Comment by KnorpelSenf** [comment]
> I wonder why globes? In my opinion, they are not suitable because they only depict three major regions of the Earth: America, Africa and Asia. Why not use a flag emojis, for example?

Which continents are you missing? Antarctica?

**Comment by KnorpelSenf** [comment]
> We could use a single globe for all languages if the displayed regions are a problem.

Dropping the rotation part effectively puts a single continent into focus, which isn't exactly better. Using 🌐 looks ugly.

**Comment by Nazar-Ant** [comment]
Have you considered using a [similar icon](https://fontawesome.com/icons/language?s=solid&f=classic)?

**Comment by roj1512** [comment]
I mean, I’m not a designer but I think it would need a lot of thinking to choose a suitable external icon.

**Comment by KnorpelSenf** [comment]
> Have you considered using a [similar icon](https://fontawesome.com/icons/language?s=solid&f=classic)?

No. So far, we have only considered Unicode characters for simplicity. Does the globe bother you that much?

**Pull request merged**
