### PR TITLE
Fix build error

### PR DESCRIPTION
**Pull request by quadratz**
Error: `Rollup failed to resolve import "mrmime"`

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Uhm … could you say a few words about why the build error was caused, and how these changes fix it? I have no idea what this is doing.

**Comment by quadratz** [comment]
We just simply sync the changes from Vitepress (node_modules).

The error: `Rollup failed to resolve import 'mrmime'` comes from this line:
https://github.com/grammyjs/website/blob/512dabe4bd55865f94a1215d8a31c37ffd4ba891/site/docs/.vitepress/deps/utils.ts#L2
which no longer exists in the latest Vitepress

**Review by KnorpelSenf — APPROVED** [review]
Alright!

**Review by roj1512 — APPROVED** [review]
I couldn’t understand it well, but I know it’s something good. Thank you!

**Comment by roj1512** [comment]
And sign your commits next time.

**Pull request merged**
