### PR TITLE
Add a note about the importance of correct combination of context flavors

### PR DESCRIPTION
**Pull request by KnorpelSenf**
As asked in https://t.me/grammyjs/81154 and many times before

### CODE REVIEW

**Comment by WingLim** [comment]
@KnorpelSenf I dont know why my vscode will merge `bot-feats` into this branch, can you please rebase to [9c7a673](https://github.com/grammyjs/website/pull/514/commits/9c7a6737d4c2f5e6506c0ce34d8e9ab0538f5744) then I start over Chinese part?

**Comment by KnorpelSenf** [comment]
I prefer not to force-push because that makes it hard to understand what happened. We squash-merge anyway, so the main branch will have a clean history. I reverted all changes and undid everything since 9c7a6737d4c2f5e6506c0ce34d8e9ab0538f5744 in a single commit.

**Comment by KnorpelSenf** [comment]
Or maybe I did not do that? 🤔

**Comment by KnorpelSenf** [comment]
Ah I cannot undo merges, that's unfortunate. Then I'll make an exception and force-push …

**Comment by KnorpelSenf** [comment]
@WingLim you can now hard-reset your branch to the remote and do it again :)

**Comment by WingLim** [comment]
> Ah I cannot undo merges, that's unfortunate. Then I'll make an exception and force-push …

It already confuse me. Anyway, I push back the EN, ID and ZH changes of `contenxt.md` to this branch.

**Comment by WingLim** [comment]
> > Ah I cannot undo merges, that's unfortunate. Then I'll make an exception and force-push …
> 
> It already confuse me. Anyway, I push back the EN, ID and ZH changes of `contenxt.md` to this branch.

Is it a GitHub bug? Why this branch contain #521 commits.

**Comment by KnorpelSenf** [comment]
I am honestly not sure what is going on here.

**Review by habemuscode — APPROVED** [review]
Merging with main, `config.ts` changes disappear that is the expected behavior

**Review by roj1512 — APPROVED** [review]

**Pull request merged**
