### PR TITLE
Add Heroku to hosting

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Adds a Heroku deployment tutorial

### CODE REVIEW

**Comment by CikiMomogi** [comment]
It's ready for review. As usual, please check for grammar error 🙂

**Comment by KnorpelSenf** [comment]
Cool stuff! That's a great tutorial, thanks a bunch!

I'm going to fix a few typos and I'm actually going to follow it through once to confirm that no step is ambiguous. It looks really good, though.

Planning on getting this done and merged before the end of the week.

**Comment by KnorpelSenf** [comment]
I don't have push permission to this branch, so I cannot add my fixes to this PR. I simply performed the merge locally now and directly pushed `main`. Your changes are live already.

**Comment by CikiMomogi** [comment]
Great!

**Pull request merged**
