### PR TITLE
Use "std/http" adapter for Vercel Edge Functions, instead of "https"

### PR DESCRIPTION
**Pull request by Hth4nh**

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Where do the translations come from? Are you a native speaker in all of these languages?

**Comment by KnorpelSenf** [comment]
Oh. I see. Please revert them. We have a team of translators that will take care of this. It is better to leave translations to them and only submit changes to the English version. 

An exception can be made if a pull request only touches code snippets (such as in #1164) but not here.

**Comment by Hth4nh** [comment]
> Oh. I see. Please revert them. We have a team of translators that will take care of this. It is better to leave translations to them and only submit changes to the English version.
> 
> An exception can be made if a pull request only touches code snippets (such as in #1164) but not here.

Should the outdated line be replaced with an English version so that the translation team can re-translate it later? Or just revert it to its original state?

**Review by KnorpelSenf — APPROVED** [review]
Thanks!

I also fixed up a few more things, this is ready for translation now

**Review by rojvv — APPROVED** [review]

**Review by habemuscode — APPROVED** [review]

**Comment by habemuscode** [comment]
Translations PR: https://github.com/grammyjs/website/pull/1169

This can be merged when reviewed

**Pull request merged**
