### PR TITLE
Fix typo in the holy name

### PR DESCRIPTION
**Pull request by rojserbest**

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
Thanks!

**Comment by rojserbest** [comment]
@KnorpelSenf, should we replace all `Node`s with `Node.js`?

**Comment by KnorpelSenf** [comment]
I do not think this is necessary. Both forms are used a lot, even by the Node(.js) team themselves. I already put an explanation here: https://grammy.dev/guide/introduction.html#prerequisites-to-getting-started

> “If you see people call [Node.js] Node, they are just too lazy to type ‘.js’, but they mean the same thing.”

**Comment by rojserbest** [comment]
I just thought it's uncool to have both variants on a single page.

**Comment by KnorpelSenf** [comment]
I don't mind, but I also don't have strong opinions on the issue. You can change it to be consistent if you want :)

**Pull request merged**
