### PR TITLE
Respond after exiting the conversation

### PR DESCRIPTION
**Pull request by roziscoding**
As suggested on https://t.me/grammyjs/85155

### CODE REVIEW

**Review by KnorpelSenf — COMMENTED** [review]
Could you adjust all languages?

**Review by KnorpelSenf — APPROVED** [review]
Thanks!

**Review by roj1512 — APPROVED** [review]
LGTM. Thank you so much!

**Comment by roj1512** [comment]
@roziscoding Anytime :)

**Pull request merged**
