### PR TITLE
[Translations] [Indonesian]: /id/readme.md

### PR DESCRIPTION
**Pull request by CikiMomogi**

### CODE REVIEW

**Comment by roj1512** [comment]
Is this a joke?

**Comment by CikiMomogi** [comment]
> Is this a joke?

Is something wrong?

**Comment by roj1512** [comment]
Why are you making a pull request to here? It should be to your fork.

**Comment by KnorpelSenf** [comment]
I may have been imprecise when I said that pull requests should go against `main` 😅
I mean the `main` branch of the fork, not of this repo, sorry

**Comment by CikiMomogi** [comment]
Lol. Forgive me everyone. The PR notification from was pretty annoying for sure.

**Comment by KnorpelSenf** [comment]
No problem :)

**Comment by KnorpelSenf** [comment]
Closing in favour of https://github.com/CikiMomogi/website/pull/7

**Pull request closed without merging**
