### PR TITLE
Improve headings

### PR DESCRIPTION
**Pull request by roziscoding**
Previous titles were a bit weird and misleading since the examples don't really show any "routes"

### CODE REVIEW

**Review by roj1512 — COMMENTED** [review]
Is this really not translatable?

**Comment by roziscoding** [comment]
To be fair, I assumed it isn't, but I don't have the knowledge of other languages to check their versions so I guess it's better to remove the label

**Review by roj1512 — APPROVED** [review]

**Comment by niusia-ua** [comment]
@LWJerri @deptyped Do we need to correct this? In our translation, we used the word "обробник" (in English, "handler"), which is essentially the same as "route". Based on the meaning of the text and code examples, I don't think we need to change anything.

**Comment by LWJerri** [comment]
> обробник

In my opinion, we can do translating to "В разовому випадку" та "У всіх випадках". But yes, my suggestion is not word-to-word translation with original file, so idk.

**Review by LWJerri — APPROVED** [review]

**Review by roj1512 — APPROVED** [review]

**Review by habemuscode — APPROVED** [review]

**Pull request merged**
