### PR TITLE
Undo Spanish translations of the code

### PR DESCRIPTION
**Pull request by faloi**
Seems like some chunks of code were wrongly translated to Spanish. I've changed them to be in English again. 😃

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Oh wow, @habemuscode how did that happen?

@faloi thanks!

**Review by roj1512 — APPROVED** [review]
LGTM. Thank you so much!

**Comment by KnorpelSenf** [comment]
@faloi are you interested in joining in on the Spanish translations? There are still a number of untranslated things for Spanish in the list of open pull requests. You could have a substantial impact here and accelerate things greatly if you'd help :)

**Comment by faloi** [comment]
> @faloi are you interested in joining in on the Spanish translations? There are still a number of untranslated things for Spanish in the list of open pull requests. You could have a substantial impact here and accelerate things greatly if you'd help :)

I live in a van, and I'm traveling through Latin America right now, so I can't commit to a new project right now. But from time to time I can make small contributions like this one. 

I will ask for help on my YouTube videos too, perhaps any of the people who watch them can join the team. 😁

**Comment by KnorpelSenf** [comment]
Sounds like a plan! Have a safe journey :D

**Pull request merged**
