### PR TITLE
Add @satont/grammy-psql-storage into session section

### PR DESCRIPTION
**Pull request by Satont**
Locked by https://github.com/Satont/grammy-psql-storage/pull/1

### CODE REVIEW

**Comment by Satont** [comment]
Ready for merge.

/cc @KnorpelSenf

**Comment by KnorpelSenf** [comment]
I don't know what happened here, but this is impossible to review. Can you create a new branch at the same commit and open a new PR that closes this one?

**Comment by Satont** [comment]
> I don't know what happened here, but this is impossible to review. Can you create a new branch at the same commit and open a new PR that closes this one?

I am by mistake did `git pull main -r` and pushed it here. Yea, i'll do another PR.

**Review by KnorpelSenf — APPROVED** [review]
LGTM

**Pull request merged**
