### PR TITLE
[Feat] [Translations] [Spanish]: advanced/deployment

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by habemuscode** [comment]
Pushed master and fix a typo, from my side, ready @KnorpelSenf @roj1512

**Comment by roj1512** [comment]
@habemuscode what's ready? this PR?

**Comment by habemuscode** [comment]
@roj1512 Translation is done, and I merge with main branch (forget to push the feat branch, now you will see less diff :) )

**Comment by roj1512** [comment]
@habemuscode Please speak clearly. I don't understand you.

**Comment by KnorpelSenf** [comment]
After merging main, the translation branch wasn't pushed. This led to a huge diff between this feature branch and the translation branch, which made the PQ difficult to review. By pushing the translation branch, this was fixed now, so the PQ now has a small diff again.

Translating @habemuscode ←→ English 😁❤️

**Comment by roj1512** [comment]
Cool.

**Review by habemuscode — APPROVED** [review]

**Pull request merged**
