### PR TITLE
Finalize #585

### PR DESCRIPTION
**Pull request by CikiMomogi**
Re-open https://github.com/grammyjs/website/pull/585 due to accidentally merged

### CODE REVIEW

**Comment by CikiMomogi** [comment]
@fadzikri Could you please review the Indonesian doc again. A lot of changes have taken place. Thanks.

**Comment by fadzikri** [comment]
Weird, i don't see [+] button except in edited line. So, i edited the file directly.

**Review by fadzikri — APPROVED** [review]
OK

**Review by fadzikri — APPROVED** [review]
I have re-read the page. Good sentences and words choices.

**Review by habemuscode — APPROVED** [review]

**Review by roj1512 — APPROVED** [review]
LGTM.

**Pull request merged**
