### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by quadratz**
`deno task check-links`

Only these kinds of issues are intentionally left unresolved:
>site/docs/guide/filter-queries.md (3)
>— The link https://deno.land/x/grammy/filter.ts?s=matchFilter responded with a not OK status code 404. It says "Not Found"
>— The link https://deno.land/x/grammy/filter.ts?s=Filter responded with a not OK status code 404. It says "Not Found"
>— The link https://deno.land/x/grammy/filter.ts?s=FilterQuery responded with a not OK status code 404. It says "Not Found"

### CODE REVIEW

**Comment by quadratz** [comment]
> site/docs/zh/hosting/firebase.md (1)
> — The link https://accounts.google.com/signup was redirected to https://accounts.google.com/signup/v2?flowEntry=SignUp&flowName=GlifWebSignIn&theme=glif.

Should we fix this redirect too? The redirect in my browser is https://accounts.google.com/signup/v2/createaccount?theme=glif&flowName=GlifWebSignIn&flowEntry=SignUp. Perhaps yours is different as well?

**Comment by KnorpelSenf** [comment]
> `deno task check-links`
> 
> Only these kinds of issues are intentionally left unresolved:
> 
> > site/docs/guide/filter-queries.md (3)
> > — The link [deno.land/x/grammy/filter.ts?s=matchFilter](https://deno.land/x/grammy/filter.ts?s=matchFilter) responded with a not OK status code 404. It says "Not Found"
> > — The link [deno.land/x/grammy/filter.ts?s=Filter](https://deno.land/x/grammy/filter.ts?s=Filter) responded with a not OK status code 404. It says "Not Found"
> > — The link [deno.land/x/grammy/filter.ts?s=FilterQuery](https://deno.land/x/grammy/filter.ts?s=FilterQuery) responded with a not OK status code 404. It says "Not Found"

Please change it to use https://deno.land/x/grammy@v1.19.2/mod.ts?s=matchFilter etc (replace `filter.ts` by `mod.ts` in all three links).

> > site/docs/hosting/firebase.md (1)
> > — The link [accounts.google.com/signup](https://accounts.google.com/signup) was redirected to [accounts.google.com/signup/v2?flowEntry=SignUp&flowName=GlifWebSignIn&theme=glif](https://accounts.google.com/signup/v2?flowEntry=SignUp&flowName=GlifWebSignIn&theme=glif).
> 
> Should we fix this redirect too? The redirect in my browser is [accounts.google.com/signup/v2/createaccount?theme=glif&flowName=GlifWebSignIn&flowEntry=SignUp](https://accounts.google.com/signup/v2/createaccount?theme=glif&flowName=GlifWebSignIn&flowEntry=SignUp). Perhaps yours is different as well?

Mine actually is https://accounts.google.com/lifecycle/steps/signup/name with some long query parameters added to that. I would suggest to keep it as-is unless someone has a better idea. @dcdunkan is there a way to tell the link checker to not check certain links? I forgot

**Comment by dcdunkan** [comment]
@dcdunkan is there a way to tell the link checker to not check certain links? I forgot

Yes, we can ignore certain links. In the `fetch.ts` file of link checker.

**Comment by KnorpelSenf** [comment]
@dcdunkan nice, thanks. @quadratz could you add the link there?

**Comment by quadratz** [comment]
https://github.com/grammyjs/link-checker/pull/13

**Comment by KnorpelSenf** [comment]
@quadratz is this ready?

**Comment by quadratz** [comment]
Yes, It is ready to merge.

**Review by roj1512 — APPROVED** [review]
Thank you!

**Pull request merged**
