### PR TITLE
Fix invalid links

### PR DESCRIPTION
**Pull request by CikiMomogi**

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
Nice catch. Do you know why they were outdated?

**Review by roj1512 — APPROVED** [review]
Thanks!

**Comment by roj1512** [comment]
@KnorpelSenf It was because of my somehow blindly done .md and .html replacements.

**Comment by KnorpelSenf** [comment]
Ah I see, alright. Great it's fixed!

**Pull request merged**
