### PR TITLE
Add section with common errors to FAQ

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Requested by @darvesh in https://t.me/grammyjs/26591 and by @Tecardo1 in https://t.me/grammyjs/25116.

### CODE REVIEW

**Review by habemuscode — APPROVED** [review]
LGTM. It's a great idea to reduce the amount of similar questions

**Comment by darvesh** [comment]
LGTM.

**Comment by KnorpelSenf** [comment]
@WingLim my apologies, I should not have merged yet. Could you create a follow-up PR with the translations? I restored the branch in case the local diff helps you.

**Comment by WingLim** [comment]
> @WingLim my apologies, I should not have merged yet. Could you create a follow-up PR with the translations? I restored the branch in case the local diff helps you.

Sure, no worries.

**Pull request merged**
