### PR TITLE
Convert colors to hex

### PR DESCRIPTION
**Pull request by roj1512**
- This lets us have [a clean palette](https://www.figma.com/file/Q06hKgDveVPxeKnxnn9dlT/grammY-colors).

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]

**Comment by roj1512** [comment]
Waiting for an opinion regarding https://github.com/grammyjs/website/pull/381#issuecomment-1136347202.

**Comment by Loskir** [comment]
you seem to have forgotten to change the token color. it's 009dca too

**Comment by Loskir** [comment]
изображение
and also the dark colors

**Comment by roj1512** [comment]
> you seem to have forgotten to change the token color. it's 009dca too

Do you mean this?

image

**Comment by roj1512** [comment]
@Loskir Thanks, I corrected it. Can you give this a review?

**Comment by roj1512** [comment]
I forgot to change the colors of almost everything Ха-Ха-Ха.

**Pull request merged**
