### PR TITLE
Update dependencies to fix vulnerabilities

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by roj1512** [comment]
I'm not sure if we will be safe.

**Comment by KnorpelSenf** [comment]
What does that mean?

**Comment by roj1512** [comment]
It means I'm not sure if doing that breaks things or not.

**Comment by KnorpelSenf** [comment]
No one knows this until we try, that's why I'm suggesting to give it a shot :)
If it does break, we will see it. Then we can revert and report the bug etc

**Comment by roj1512** [comment]
@KnorpelSenf Vulnerabilities can't be fixed if we upgrade the dependencies.

**Comment by KnorpelSenf** [comment]
Why not?

**Comment by roj1512** [comment]
Try it yourself.

**Comment by roj1512** [comment]
@KnorpelSenf This is not a draft, you're trying to change its goal.

**Comment by KnorpelSenf** [comment]
That's a vuln in the deps. Usually updating deps helps, and we need to do this anyway again, so why not do it now? The goal is to be up to date so that we avoid vulns.

Draft because there are pending discussions that need to be resolved, so this isn't ready to merge.

**Comment by roj1512** [comment]
Pending discussions could be in a different PR that does the dependency upgrades. I thought you were just meaning to remove the vulnerability alerts at first.

**Comment by KnorpelSenf** [comment]
I was, but in the most future-proof way, which would be not to rely on months-old beta versions. Do you feel like this needs to be merged fast?

**Comment by roj1512** [comment]
Well, that's a thing, too. The warning can be nothing.

**Comment by roj1512** [comment]
Drafting it again

**Comment by KnorpelSenf** [comment]
> @KnorpelSenf Vulnerabilities can't be fixed if we upgrade the dependencies.

I do not understand what you mean. It seems to me like all vulnerabilities are fixed if VuePress is updated to the most recent version. In addition, some bugs are fixed. For example, the production site does not remove the header anchor from the URL when scrolling to the top.

**Comment by KnorpelSenf** [comment]
```sh
$ npm audit
found 0 vulnerabilities
```

**Review by KnorpelSenf — APPROVED** [review]

**Pull request merged**
