### PR TITLE
Fix syntax highlighting light theme in API ref

### PR DESCRIPTION
**Pull request by quadratz**
The syntax color in the ref docs (dracula-theme) is hard to read in light mode and it does not match the current theme (github-theme). This PQ should resolve the issue.

Before (dracula-theme):
before
After (github-theme):
after

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
> it does not match the current theme (github-theme)

And by current theme you mean the current theme for code snippets in light mode for the rest of the website?

**Review by roj1512 — APPROVED** [review]
Thank you so much! I had this in mind but never knew what the best practice would be.

**Comment by quadratz** [comment]
> And by current theme, you mean the current theme for code snippets in light mode for the rest of the website?

Yes. Previously, it only used one theme, which was designed for dark mode only. Now it should use two different themes for both light mode and the dark mode, like we already do with the rest of the website.

**Comment by quadratz** [comment]
> Thank you so much! I had this in mind but never knew what the best practice would be.

I also feel uncomfortable with hardcoding the values. It should be done dynamically. But at least this is what we can do for now.

**Pull request merged**
