### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by abdoo9**

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
Thanks! Nice catch

**Review by roj1512 — APPROVED** [review]
LGTM. Thank you so much!

**Comment by KnorpelSenf** [comment]
@roj1512 does CI fail because the commit on main does not have the correct labels? Does this mean we should add a check for the branch?

**Comment by KnorpelSenf** [comment]
No wait, it succeeds on main … what's going on here

**Comment by roj1512** [comment]
No idea.

**Comment by roj1512** [comment]
I think we should debug it.

**Pull request merged**
