### PR TITLE
Simplify import

### PR DESCRIPTION
**Pull request by PonomareVlad**
As we [tested](https://github.com/grammyjs/grammY/pull/441) earlier, the `"browser"` target in the `"exports"` field is already supported by **Vercel Edge** and **Cloudflare Workers**

I suggest shortening the optional import from the `web` path to get more generic examples

[Example source](https://github.com/PonomareVlad/grammYExportsTest/blob/cloudflare/bot.mjs#L1)

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]
Thank you!

**Comment by roj1512** [comment]
Hmm seems like there is nothing to do here. The imports were already replaced to deno.land/x in main.

**Comment by KnorpelSenf** [comment]
Perhaps we should do the same for Vercel?

**Comment by roj1512** [comment]
Convert to deno.land/x import or just grammy?

**Comment by KnorpelSenf** [comment]
I was thinking of using `grammy` instead of `grammy/web` but now that you ask about it, we might actually migrate the guides to the new deno-based service by vercel, right?

**Comment by roj1512** [comment]
What is the new deno-based service by vercel?

**Comment by KnorpelSenf** [comment]
https://vercel.com/docs/functions/edge-functions is based on https://deno.com/subhosting

**Comment by roj1512** [comment]
Oh that makes Sense

**Comment by roj1512** [comment]
I’ll leave that decision to our VP of Serverless, @PonomareVlad.

**Comment by PonomareVlad** [comment]
> Hmm seems like there is nothing to do here. The imports were already replaced to deno.land/x in main.

@roj1512 [There is to do](https://github.com/grammyjs/website/pull/916)

**Comment by roj1512** [comment]
Thanks!

**Comment by roj1512** [comment]
What are your thoughts on https://github.com/grammyjs/website/pull/834#issuecomment-1762788608, @PonomareVlad?

**Comment by PonomareVlad** [comment]
> What are your thoughts on https://github.com/grammyjs/website/pull/834#issuecomment-1762788608, @PonomareVlad?

[There is no any Deno-based service in Vercel](https://t.me/grammyjs/175428?thread=175413) 🌚

**Comment by PonomareVlad** [comment]
Except [this community builder for Serverless Functions ](https://github.com/vercel-community/deno)

**Comment by roj1512** [comment]
What about their Edge Runtime? https://github.com/grammyjs/website/pull/834#issuecomment-1762797800

**Comment by PonomareVlad** [comment]
> What about their Edge Runtime? https://github.com/grammyjs/website/pull/834#issuecomment-1762797800

Earlier I think about extending Vercel guide for Edge Runtime case, but we need to test which grammY plugins still incompatible with it and notify about this before announcing compatibility 🌚

**Comment by roj1512** [comment]
So you mean the `grammy` import is better for now, right?

**Comment by PonomareVlad** [comment]
> So you mean the `grammy` import is better for now, right?

Is similar to `grammy/web`

**Comment by roj1512** [comment]
So it’ll be fine for Vercel, right?

**Comment by PonomareVlad** [comment]
> So it’ll be fine for Vercel, right?

Including Vercel, right

**Comment by roj1512** [comment]
Can you create a PQ for that?

**Comment by PonomareVlad** [comment]
Yes, but it depends on:

> > What about their Edge Runtime? https://github.com/grammyjs/website/pull/834#issuecomment-1762797800
> 
> Earlier I think about extending Vercel guide for Edge Runtime case, but we need to test which grammY plugins still incompatible with it and notify about this before announcing compatibility 🌚
> 
> [For example](https://github.com/grammyjs/conversations/pull/82#issuecomment-1751989236)

**Comment by roj1512** [comment]
I meant for the Node.js example, not their edge runtime.

**Comment by PonomareVlad** [comment]
> I meant for the Node.js example, not their edge runtime.

In docs or in repo with examples ?

**Pull request closed without merging**
