### PR TITLE
Perf is nice

### PR DESCRIPTION
**Pull request by KnorpelSenf**

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]

**Review by quadratz — CHANGES_REQUESTED** [review]

**Review by habemuscode — APPROVED** [review]

**Comment by roj1512** [comment]
@quadratz PTAL

**Comment by quadratz** [comment]
@dzikrl PTAL https://github.com/grammyjs/website/pull/999#discussion_r1506789722

**Review by quadratz — APPROVED** [review]

**Comment by quadratz** [comment]
@roj1512 Feel free to merge this PQ if there is no response from @dzikrl in the next 3 days

**Comment by quadratz** [comment]
Yup. You could simply accept or reject the suggested changes with little notes before approving the PQ

**Comment by quadratz** [comment]
@roj1512 it's ready to merge now

**Pull request merged**
