### PR TITLE
docs: translate zh/plugins/console-time

### PR DESCRIPTION
**Pull request by WingLim**
- [x] console-time.md

@KnorpelSenf  It seems that this plugin doesn't add to nav, is this on purpose?

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
> It seems that this plugin doesn't add to nav, is this on purpose?

It is a third-party plugin. It is not part of @grammyjs. This means it has a lot fewer guarantees, details about third-party plugins are outlined [here](https://github.com/grammyjs/grammY/blob/main/CONTRIBUTING.md#how-to-contribute).

The plugin is linked [here in the navigation](https://github.com/grammyjs/website/blob/main/site/docs/.vuepress/config.ts#L221-L224).

**Comment by WingLim** [comment]
> It is a third-party plugin. It is not part of @grammyjs. This means it has a lot fewer guarantees, details about third-party plugins are outlined [here](https://github.com/grammyjs/grammY/blob/main/CONTRIBUTING.md#how-to-contribute).
> 
> The plugin is linked [here in the navigation](https://github.com/grammyjs/website/blob/main/site/docs/.vuepress/config.ts#L221-L224).

Oh, so sorry for that, I didn't notice it at first.

**Comment by KnorpelSenf** [comment]
No problem :)
It is indeed a little hidden because it's the only entry on that list

**Review by linbuxiao — APPROVED** [review]
:star_struck:

**Pull request merged**
