### PR TITLE
Fix issues in code examples

### PR DESCRIPTION
**Pull request by evshiron**

### CODE REVIEW

**Review by roj1512 — COMMENTED** [review]
Can you also fix the typo in the corresponding `/{lang_code}/advanced/proxy.md` files?

**Review by roj1512 — COMMENTED** [review]
One more to go

- `/site/docs/es/advanced/proxy.md`

**Comment by evshiron** [comment]
Done.

Btw, when I follow the English tutorial, `TypeError: No "host"` occurred. Looks like it has been renamed:

https://github.com/TooTallNate/node-socks-proxy-agent/blob/master/src/index.ts#L28

**Comment by KnorpelSenf** [comment]
Yep: https://github.com/TooTallNate/node-socks-proxy-agent/pull/97

**Comment by evshiron** [comment]
Should I modify them as well?

**Comment by KnorpelSenf** [comment]
Yes please! That'd be great, thanks

**Comment by evshiron** [comment]
Done.

Previous commits are created by editing on GitHub one by one, which might be too ugly. Squashing requested.

**Comment by KnorpelSenf** [comment]
Thank you! We squash everything anyway :)

**Review by roj1512 — APPROVED** [review]
LGTM. Thank you so much!

**Pull request merged**
