### PR TITLE
Correct transformer examples

### LINKED ISSUE #233: Installing API request transformer prevents bot stop
## Problem

Installing an (even empty) API request transformer makes bot stuck on `bot.stop()` until the next update arrives.

## Reproduction

```ts
import { Bot } from "grammy"

function log(text: string) {
  console.log(`${new Date().toISOString()}: ${text}`)
}

const bot = new Bot(process.env.BOT_TOKEN)

// This makes the bot stuck on stop()
bot.api.config.use((prev, method, payload) => prev(method, payload))

bot.command("start", async (ctx) => {
  log("/start handler")
  await ctx.reply(`Welcome here.`)
})

setTimeout(async () => {
  log("calling bot.stop()")
  await bot.stop().then(() => log("bot.stop() completed"))
}, 5000) // <--- 3000 or smaller doesn't cause the bug.

log("calling bot.start()")
bot.start().then(() => log("bot.start() completed"))
```

### Result

```
2022-02-08T05:26:56.329Z: calling bot.start()
2022-02-08T05:27:01.330Z: calling bot.stop()
2022-02-08T05:27:01.614Z: bot.stop() completed
2022-02-08T05:27:13.227Z: /start handler <------ this is when I sent /start to the bot
2022-02-08T05:27:13.613Z: bot.start() completed
```

This repeats consistently.

Removing the request transformer fixes the problem:

```
2022-02-08T05:32:05.909Z: calling bot.start()
2022-02-08T05:32:10.909Z: calling bot.stop()
2022-02-08T05:32:10.915Z: bot.start() completed
2022-02-08T05:32:11.297Z: bot.stop() completed
```

## Environment

grammy@1.7.0
node 16.13.0

I know this all sounds odd, but I was getting the problem consistently in production, then started to reduce code until I arrived at this minimum reproduction repo.

### PR DESCRIPTION
**Pull request by roj1512**
- Closes #233.

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
Thanks!

**Comment by KnorpelSenf** [comment]
@habemuscode please also sync #182

**Comment by KnorpelSenf** [comment]
> @habemuscode please also sync #182

This isn't blocking.

**Review by WingLim — APPROVED** [review]
Great job!

**Comment by roj1512** [comment]
The label removals were for testing a webhook.

**Pull request merged**
