### PR TITLE
Repair broken links of formatting options

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
Thanks! <3

**Comment by KnorpelSenf** [comment]
Actually, the links are still working. What does not work is the creation of the links, as the buttons are missing. Should we perhaps close this unmerged?

**Comment by KnorpelSenf** [comment]
Actually, the links are still working. What does not work is the creation of the links, as the buttons are missing. Should we perhaps close this unmerged?

**Comment by KnorpelSenf** [comment]
It seems fixed completely by Telegram now.

**Comment by roj1512** [comment]
Better I didn’t find time to merge. :D

**Pull request closed without merging**
