### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Not sure if this was clear, contributors obviously don't need to translate anything.

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
Feel free to delete branches after merging

**Comment by roj1512** [comment]
@refined-github he was talking to you

**Comment by roj1512** [comment]
@fregante Is there a reason branches are not deleted after merging? I am on Firefox.

**Comment by fregante** [comment]
Check the options page. The feature was disabled

**Comment by roj1512** [comment]
Oh, thanks letting me know

**Comment by fregante** [comment]
The feature has been restored 👌

**Comment by roj1512** [comment]
Wow, that was fast!

**Comment by KnorpelSenf** [comment]
Thank you so much!

**Comment by fregante** [comment]
The underlying bug still exists, but it wasn't as bad as thought, so I dropped the "remote disable" for the feature. 😅

**Pull request merged**
