### PR TITLE
Never use empty lines around tips

### PR DESCRIPTION
**Pull request by KnorpelSenf**
This was done inconsistently across all languages and within every language.

From now on, we use
- no blank lines inside a tip next to the boundaries
- blank lines surrounding a tip
- blank lines inside a tip surrounding code snippets, even if they are next to a tip
- blank before the closing tag of the tip if the tip content ends with a list entry
- blank before the closing tag of the tip if the tip content ends with a quote

The same applies for other `:::` environments, not just tips.

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
I was faster

**Comment by KnorpelSenf** [comment]
But how did you commit the same changes?

**Comment by roj1512** [comment]
I have null idea

**Comment by KnorpelSenf** [comment]
GH race condition

**Pull request merged**
