### PR TITLE
Migrate back to the Deno-powered sitemap generation

### PR DESCRIPTION
**Pull request by KnorpelSenf**
This is good now, I fixed up a lot of things and it produces the same `sitemap.xml` file now. The only difference is that it has a better sorting than `sscli`.

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]
LGTM.

**Comment by CikiMomogi** [comment]
I don't know much about XML, but I'm wondering if the double slash `//` in the URL is valid?
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://grammy.dev//404.html</loc>
        <lastmod>2023-03-04T17:10:07.523Z</lastmod>
    </url>
    ...
    <url>
        <loc>https://grammy.dev//resources/faq.html</loc>
        <lastmod>2023-03-04T17:09:55.590Z</lastmod>
    </url>
</urlset>
```

**Comment by CikiMomogi** [comment]
> It is not. Where do you see this?

Oh nvm. It's good now. I forgot to run `docs:sitemap` :P

**Comment by KnorpelSenf** [comment]
> > It is not. Where do you see this?
> 
> Oh nvm. It's good now. I forgot to run `docs:sitemap` :P

Okay awesome! This and #660 were supposed to fix exactly that issue 😅

**Pull request merged**
