### PR TITLE
Improve consistency of code block names

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by roj1512** [comment]
I’m also thinking of adding a workflow to enforce this along with some other custom rules.

**Review by KnorpelSenf — APPROVED** [review]
Did you check if TS is the only affected tag?

LGTM.

**Comment by KnorpelSenf** [comment]
> I’m also thinking of adding a CI to enforce this along with some other custom rules.

I have Markdown linting in VSC, perhaps there's a CLI for CI.

**Comment by roj1512** [comment]
@KnorpelSenf I fixed bash and markdown, too

**Review by KnorpelSenf — APPROVED** [review]
Nice!

**Pull request merged**
