### PR TITLE
Update color scheme

### PR DESCRIPTION
**Pull request by Loskir**

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]
Thank you, this is amazing!

**Comment by roj1512** [comment]
@Loskir I don't see a big difference between the Brand Dark and Tip colors in the different modes, should we merge them?
image

**Comment by Loskir** [comment]
these colors were obtained by hue-shifting the [default colors](https://v2.vuepress.vuejs.org/reference/default-theme/styles.html#style-file) in OKLCH color model using [this wonderful tool](https://oklch.evilmartians.io/). 
изображение
here's a closer look at them

**Comment by Loskir** [comment]
изображение
here's a comparison

**Pull request merged**
