### PR TITLE
Update supported Bot API version

### PR DESCRIPTION
**Pull request by KnorpelSenf**
See https://github.com/grammyjs/grammY/pull/273

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
No translation this time?

**Comment by KnorpelSenf** [comment]
Well, at least the branch was deleted correctly.

**Comment by roj1512** [comment]
lol

**Comment by roj1512** [comment]
Yes, no translation. It is time-sensitive.

**Comment by KnorpelSenf** [comment]
Fair point

**Pull request merged**
