### PR TITLE
Handle deleted accounts

### PR DESCRIPTION
**Pull request by quadratz**
Screenshot 2023-12-09 at 16-31-42 grammY

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
This PQ broke the component, it isn't being displayed as all anymore now.

**Comment by quadratz** [comment]
image
Seems fine to me. :thinking:

**Comment by KnorpelSenf** [comment]
Can you try it with the time set to the moment I posted the above comment?

**Comment by quadratz** [comment]
> This PQ broke the component, it isn't being displayed at all anymore now.

https://github.com/grammyjs/website/pull/979

**Pull request merged**
