### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by rojserbest**

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Be sure to follow the formatting and linting rules of Deno. This will make CI pass.

**Comment by rojserbest** [comment]
I'm planning to have full stops in the end of the comments which include verbs. Also, make all comments start with a capital letter. Lmk if this is good or not.

**Comment by KnorpelSenf** [comment]
> Also, make all comments start with a capital letter. Lmk if this is good or not.

I'd rather have @CalsiBotDev comment on that. He's amazing at these fine-grained decisions.

**Comment by rojserbest** [comment]
Super!

**Review by KnorpelSenf — CHANGES_REQUESTED** [review]
Please stick with the convention of having one sentence per line. Not following this will lead to unreadable git diffs because whole paragraphs will reflow if a single word is added or removed.

**Comment by KnorpelSenf** [comment]
This may be interesting: https://github.com/grammyjs/website#checking-correct-formatting-of-docs

**Comment by rojserbest** [comment]
Transferred to #104.

**Pull request closed without merging**
