### PR TITLE
Include deno.land/std in current-versions plugin

### PR DESCRIPTION
**Pull request by dcdunkan**

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]
LGTM. Thank you so much!

**Comment by KnorpelSenf** [comment]
`std` regularly has breaking changes which is why we initially omitted it from the plugin. Are we sure that updates to `std` cannot break our examples? How will this be tested?

**Comment by roj1512** [comment]
There's no breaking changes in the std, nor the Deno API, unless the module is using an unstable API.

Source: https://twitter.com/biwanczuk/status/1565305775743983624

**Comment by KnorpelSenf** [comment]
Great! Then this makes sense, thanks for the link

**Pull request merged**
