### PR TITLE
Describe how to catch errors when leaving conversations by throwing

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Explains the known pitfall reported again in https://github.com/grammyjs/grammY/issues/282, and how to fix it.

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]
LGTM. Thank you so much!

**Review by yn4v4s — APPROVED** [review]
LGTM. It's nice that we can solve this using [error boundaries](https://grammy.dev/guide/errors.html#error-boundaries). Though I would rather use `conversation.halt()` instead of throwing, when it's available in the upcoming release.

**Comment by KnorpelSenf** [comment]
Yep I see that point. I'm just waiting for people to review the pull requests before opening even more of them.

**Comment by habemuscode** [comment]
@KnorpelSenf `package.json` wasn't modify, but you push `package-lock.json` It's a mistake?

**Review by habemuscode — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
I honestly don't know anymore, perhaps there were updates to transitive deps. Should I revert?

**Pull request merged**
