### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Oops

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]
LGTM. Thank you so much!

**Comment by KnorpelSenf** [comment]
Your GH Refined extension is broken again … or was it from mobile?

**Comment by roj1512** [comment]
no no wait, this was done on another computer without the extension.

**Comment by roj1512** [comment]
although, thanks for manually doing the supposed-to-be-automated-thing

**Pull request merged**
