### PR TITLE
Update throttler docs

### PR DESCRIPTION
**Pull request by WingLim**
Releated to #271

### CODE REVIEW

**Review by roj1512 — COMMENTED** [review]
Please add dots to the end of the comments in the English version.

**Comment by WingLim** [comment]
@roj1512 If you have anything to do with the #271, you can edit it here.

**Comment by WingLim** [comment]
> 

Ok, I will do it.

**Comment by roj1512** [comment]
Yeah, thank you for reminding me about it. I would never know about it.

**Review by roj1512 — APPROVED** [review]
Thanks!

**Review by KnorpelSenf — APPROVED** [review]
Thank you!

**Pull request merged**
