### PR TITLE
Update gcf.md (WIP)

### PR DESCRIPTION
**Pull request by sartoshi-foot-dao**
**This is a MAJOR work in progress. Logging here to track progress. Not ready for merge**

## Context
I'm emulating the format of the Supabase Edge Functions hosting docs to write one for hosting grammY + Conversations plugin on Cloud Functions for Firebase. The reason I have chosen Cloud Functions for Firebase over raw Cloud Functions is for its seamless integration with Firestore, a convenient and necessary part of self-hosting your Conversations/Sessions. Firebase lowers the entry barrier for GCP's most popular services, opening the door for those wishing to mature their bots into grander projects.

Edit: conversations/sessions are out-of-scope for this PR.

## Todo

- [ ] Deployment: add secret through CLI
- [ ] Deployment: deploy function through CLI
- [ ] Deployment: locate function URL and `setWebhook` via browser, akin to Supabase guide
- [ ] Deployment: verify webhook URL with `getWebhookInfo` via browser
- [ ] Lint: 1 sentence per line!
- [ ] Lint: Fix regrettable code formatting...
- [ ] Test: Dogfood guide from clean slate

## Questions
1. While my motivation to write a guide originated from an [issue](https://github.com/grammyjs/storages/issues/118) about `conversations` and `sessions`, setting up Firebase to accommodate for these plugins i.e. installing and configuring Firestore will make this guide significantly longer the Supabase one. My eagerness to be comprehensive must not intrude on grammY's documentation principles, of which I assume brevity is one. Any advice?
2. This is my first time writing documentation; please feedback anything from glaring errors to tiny nitpicks. I'll be sure to heed your suggestions.

Edit: removed superfluous guidance for conversations/sessions. Will aim for hosting only.

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
I think it would be good to keep this separate from any particular plugin. Hosting stuff on firebase should work with or without conversations.

I understand that you need to set `ignoreUndefinedProperties: true` if you use conversations. However, this is also true if people want to delete a property from their session data by setting it to `undefined`. If anything, you could add a small note to this part and point out that we *recommend* anyone to set this option, but that it is *required* if you use the conversations plugin.

> * My eagerness to be comprehensive must not intrude on grammY's documentation principles, of which I assume brevity is one. Any advice?

Brevity isn't exactly a principle of the docs. Of course it does not make much sense to write long walls of text about tiny edge cases, but an in-depth explanation is almost always better than a high-level overview that leaves open questions.

An approach that worked well in the past is to write a detailed guide to get people started, and then provide links to other documentation pieces if people want to dive deeper. As an example, it would not make much sense here to debate the pros and cons of Firebase, let alone the inner working of that service. However, it is worth linking to our hosting comparison as well as to the Firebase docs in case someone wants to know.

**Comment by sartoshi-foot-dao** [comment]
Noted, thanks for the guidance. Will revert on Wednesday.

**Comment by KnorpelSenf** [comment]
Are you planning on describing hosting the code only? I'm not really sure if we should mix this up with storing data on Firebase, so ideally, this shouldn't talk about sessions. What do you think?

**Comment by sartoshi-foot-dao** [comment]
Aye aye Captain, just hosting. I'll make it clean and succinct, using the Supabase guide and your above suggestions as guidance. Shan't overcomplicate it!

Edited top post to reflect new goal.

**Comment by KnorpelSenf** [comment]
Amazing!

If you want to share your knowledge about Firebase, you could ask @Satont if a Firebase storage adapter would be welcome. Its README file would then document how to connect to Firebase for data storage.

**Comment by KnorpelSenf** [comment]
@sartoshi-foot-dao are you still working on this? :)

**Comment by KnorpelSenf** [comment]
Closing due to inactivity.

**Pull request closed without merging**
