### PR TITLE
[Spanish] Fix typos

### PR DESCRIPTION
**Pull request by CikiMomogi**

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]
LGTM. Thank you so much!

**Comment by CikiMomogi** [comment]
That was fast. lol

**Comment by roj1512** [comment]
That was us :)

**Comment by KnorpelSenf** [comment]
Ah lol

**Comment by roj1512** [comment]
Lol

**Comment by CikiMomogi** [comment]
:laughing:

**Pull request merged**
