### PR TITLE
these not there

### PR DESCRIPTION
**Pull request by KnorpelSenf**
I'm afraid this typo might have been translated. Can you guys check your languages?

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]

**Comment by CikiMomogi** [comment]
LGTM. No changes for ID.

**Comment by habemuscode** [comment]
Merge this before: https://github.com/grammyjs/website/pull/516 due to unsynced Spanish translations

**Comment by KnorpelSenf** [comment]
@habemuscode @WingLim could you leave a quick comment or add your labels if these changes do not affect your languages?

**Comment by habemuscode** [comment]
Ready to merge, since ZH is no longer required @roj1512  @KnorpelSenf

**Pull request merged**
