### PR TITLE
feat: add support for Bot API 6.4

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Support for https://core.telegram.org/bots/api#december-30-2022 will be added very soon in https://github.com/grammyjs/grammY/pull/349

### CODE REVIEW

**Review by roj1512 — APPROVED** [review]
LGTM.

**Comment by roj1512** [comment]
What the hell

**Comment by KnorpelSenf** [comment]
> What the hell

Yes :D

**Comment by habemuscode** [comment]
Tanslation will happen here: https://github.com/grammyjs/website/pull/575

**Comment by roj1512** [comment]
Only if you translate before the release. This PR was reverted.

**Comment by roj1512** [comment]
#575 is time-sensitive

**Comment by KnorpelSenf** [comment]
@habemuscode @CikiMomogi  #575 is not a lot, but we're going to release in 20-30 mins, so if you don't feel like doing things very soon, then you may want to update things later :)

**Pull request merged**
