### PR TITLE
Document the Fluent plugin

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Review by WingLim — APPROVED** [review]
🚀

**Review by KnorpelSenf — APPROVED** [review]
LGTM!

In the long run, we may consider to deprecate the i18n plugin. I am not sure about the chances of receiving a 2.0 release. Some community work has been going into this for almost a year now, mostly by @HeeroML and @EdJoPaTo. However, such a release does not seem imminent. Having two official plugins that solve the same problem in different ways is not optimal.

**Review by KnorpelSenf — APPROVED** [review]
LGTM!

In the long run, we may consider to deprecate the i18n plugin. I am not sure about the chances of receiving a 2.0 release. Some community work has been going into this for almost a year now, mostly by @HeeroML and @EdJoPaTo. However, such a release does not seem imminent. Having two official plugins that solve the same problem in different ways is not optimal.

**Comment by HeeroML** [comment]
I am writing you on telegram. Though replacing it isn't that bad of an idea, I would still try to finish 2.0

**Pull request merged**
