### PR TITLE
Even grannY can rock grammY! 🤘

### PR DESCRIPTION
**Pull request by PonomareVlad**
image

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
What does this even mean? 🫠

**Comment by KnorpelSenf** [comment]
If the joke is related to https://t.me/grammyjs/143749 then I don't like it lol, I wouldn't want to display a disadvantage of the name that prominently

**Comment by PonomareVlad** [comment]
Hmm, that’s right, but my comedy point was related to the play of words in the context of ease of use and an unexpected image of a granny as a developer 🌚

**Comment by PonomareVlad** [comment]
If there is no value in this PQ, I will not prevent its closure 🙂

**Comment by roj1512** [comment]
Let me take the lead.

**Pull request closed without merging**
