### PR TITLE
Remove Deta from the hosting comparison

### PR DESCRIPTION
**Pull request by TheHellRuler**
Deta is shutting down. 
Ref : https://deta.space/sunset

### CODE REVIEW

**Review by rojvv — CHANGES_REQUESTED** [review]
Please make the same changes in other languages.

**Comment by TheHellRuler** [comment]
> Please make the same changes in other languages.

Done,
Sorry for late reply.

**Review by KnorpelSenf — APPROVED** [review]
nice, thanks

**Review by rojvv — APPROVED** [review]
Thank you.

**Pull request merged**
